name: "Build Go project"

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports: 
          - 5432:5432
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        
      - name: Go Test
        run: go test -v ./..
  
